USE react_jwt_app;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS avatar_originalName VARCHAR(255) NOT NULL DEFAULT '' AFTER is_active,
  ADD COLUMN IF NOT EXISTS avatar_storedName VARCHAR(255) NOT NULL DEFAULT '' AFTER avatar_originalName,
  ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(255) NOT NULL DEFAULT '' AFTER avatar_storedName;

CREATE TABLE IF NOT EXISTS todos (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  workplace_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(100) NOT NULL,
  description VARCHAR(500) NOT NULL DEFAULT '',
  sort_order INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_todos_workplace_order (workplace_id, sort_order),
  CONSTRAINT fk_todos_workplace
    FOREIGN KEY (workplace_id) REFERENCES workplaces (id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS tickets (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  todo_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(140) NOT NULL,
  description VARCHAR(1000) NOT NULL DEFAULT '',
  sort_order INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_tickets_todo_order (todo_id, sort_order),
  CONSTRAINT fk_tickets_todo
    FOREIGN KEY (todo_id) REFERENCES todos (id) ON DELETE CASCADE
) ENGINE=InnoDB;
